FROM golang:alpine
ENV LANG=C.UTF-8
#compile linux only
ENV GOOS=linux
LABEL name="spdx"
LABEL version="1.0"
RUN apk add --update gcc g++ make wget curl bash libxslt libc-dev libxml2 libxml2-dev zip
RUN apk --no-cache add openssh curl 

ADD pkg /go/pkg
ADD src/spdx-doc /go/src/spdx-doc
ADD src/xsdprov /go/src/xsdprov
ADD config/spdx-doc-cfg.json /go/config/spdx-doc-cfg.json
ADD iepd/spdx-document /go/iepd/spdx-document
ADD xml /go/xml
ADD tmp/spdx-doc-iepd /go/tmp/spdx-doc-iepd
WORKDIR /go

RUN chmod -Rf 777 tmp
RUN go build xsdprov
RUN go build spdx-doc
RUN go install spdx-doc

EXPOSE 8080
CMD ["./spdx-doc"]