FROM golang:alpine
ENV LANG=C.UTF-8
#compile linux only
ENV GOOS=linux
LABEL name="spdx"
LABEL version="1.0"
RUN apk add --update gcc g++ make wget curl bash libxslt libc-dev libxml2 libxml2-dev zip
RUN apk --no-cache add openssh curl 

ADD pkg /go/pkg
ADD src/spdx-license /go/src/spdx-license
ADD src/xsdprov /go/src/xsdprov
ADD config/spdx-license-cfg.json /go/config/spdx-license-cfg.json
ADD iepd/spdx-license /go/iepd/spdx-license
ADD xml /go/xml
ADD tmp/spdx-license-iepd /go/tmp/spdx-license-iepd
WORKDIR /go

RUN chmod -Rf 777 tmp
RUN go build xsdprov
RUN go build spdx-license
RUN go install spdx-license

EXPOSE 8080
CMD ["./spdx-license"]