FROM golang:alpine
ENV LANG=C.UTF-8
#compile linux only
ENV GOOS=linux
LABEL name="spdx-sec-ism"
LABEL version="1.0"
RUN apk add --update gcc g++ make wget curl bash libxslt libc-dev libxml2 libxml2-dev zip
RUN apk --no-cache add openssh curl 

ADD pkg /go/pkg
ADD src/spdx-sec-ism /go/src/spdx-sec-ism
ADD src/xsdprov /go/src/xsdprov
ADD config/spdx-sec-ism-cfg.json /go/config/spdx-sec-ism-cfg.json
ADD iepd/spdx-sec-ism /go/iepd/spdx-sec-ism
ADD xml /go/xml
ADD tmp/spdx-sec-ism-iepd /go/tmp/spdx-sec-ism-iepd
WORKDIR /go

RUN chmod -Rf 777 tmp
RUN go build xsdprov
RUN go build spdx-sec-ism
RUN go install spdx-sec-ism

EXPOSE 8080
CMD ["./spdx-sec-ism"]