//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 09:32:17 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AlgorithmCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AlgorithmCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Md5"/>
 *     &lt;enumeration value="Sha1"/>
 *     &lt;enumeration value="Sha256"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AlgorithmCodeSimpleType")
@XmlEnum
public enum AlgorithmCodeSimpleType {


    /**
     * Indicates the algorithm used was MD5
     * 
     */
    @XmlEnumValue("Md5")
    MD_5("Md5"),

    /**
     * Indicates the algorithm used was SHA-1
     * 
     */
    @XmlEnumValue("Sha1")
    SHA_1("Sha1"),

    /**
     * Indicates the algorithm used was SHA256
     * 
     */
    @XmlEnumValue("Sha256")
    SHA_256("Sha256");
    private final String value;

    AlgorithmCodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AlgorithmCodeSimpleType fromValue(String v) {
        for (AlgorithmCodeSimpleType c: AlgorithmCodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
