//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 09:32:17 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationTypeCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AnnotationTypeCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="Review"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AnnotationTypeCodeSimpleType")
@XmlEnum
public enum AnnotationTypeCodeSimpleType {


    /**
     * Type of annotation which does not fit in any of the pre-defined annotation types.
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other"),

    /**
     * A Review represents an audit and signoff by an individual, organization or tool on the information for an SpdxElement.
     * 
     */
    @XmlEnumValue("Review")
    REVIEW("Review");
    private final String value;

    AnnotationTypeCodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AnnotationTypeCodeSimpleType fromValue(String v) {
        for (AnnotationTypeCodeSimpleType c: AnnotationTypeCodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
