//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 09:32:17 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for Checksum type
 * 
 * <p>Java class for ChecksumType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChecksumType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{spdx:xsd::1.0}ChecksumValue"/>
 *         &lt;element ref="{spdx:xsd::1.0}AlgorithmCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChecksumType", propOrder = {
    "checksumValue",
    "algorithmCode"
})
public class ChecksumType {

    @XmlElement(name = "ChecksumValue", required = true, nillable = true)
    protected ChecksumValueType checksumValue;
    @XmlElement(name = "AlgorithmCode", required = true, nillable = true)
    protected AlgorithmCodeType algorithmCode;

    /**
     * Gets the value of the checksumValue property.
     * 
     * @return
     *     possible object is
     *     {@link ChecksumValueType }
     *     
     */
    public ChecksumValueType getChecksumValue() {
        return checksumValue;
    }

    /**
     * Sets the value of the checksumValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChecksumValueType }
     *     
     */
    public void setChecksumValue(ChecksumValueType value) {
        this.checksumValue = value;
    }

    /**
     * Gets the value of the algorithmCode property.
     * 
     * @return
     *     possible object is
     *     {@link AlgorithmCodeType }
     *     
     */
    public AlgorithmCodeType getAlgorithmCode() {
        return algorithmCode;
    }

    /**
     * Sets the value of the algorithmCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlgorithmCodeType }
     *     
     */
    public void setAlgorithmCode(AlgorithmCodeType value) {
        this.algorithmCode = value;
    }

}
