//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 09:32:17 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the spdx.xsd._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RelationshipTypeCode_QNAME = new QName("spdx:xsd::1.0", "RelationshipTypeCode");
    private final static QName _Annotator_QNAME = new QName("spdx:xsd::1.0", "Annotator");
    private final static QName _ChecksumValue_QNAME = new QName("spdx:xsd::1.0", "ChecksumValue");
    private final static QName _ExternalDocumentID_QNAME = new QName("spdx:xsd::1.0", "ExternalDocumentID");
    private final static QName _SpecVersion_QNAME = new QName("spdx:xsd::1.0", "SpecVersion");
    private final static QName _Relationship_QNAME = new QName("spdx:xsd::1.0", "Relationship");
    private final static QName _AnnotationTypeCode_QNAME = new QName("spdx:xsd::1.0", "AnnotationTypeCode");
    private final static QName _HasExtractedLicensingInfo_QNAME = new QName("spdx:xsd::1.0", "HasExtractedLicensingInfo");
    private final static QName _Comment_QNAME = new QName("spdx:xsd::1.0", "Comment");
    private final static QName _RelatedSpdxElement_QNAME = new QName("spdx:xsd::1.0", "RelatedSpdxElement");
    private final static QName _Annotation_QNAME = new QName("spdx:xsd::1.0", "Annotation");
    private final static QName _Date_QNAME = new QName("spdx:xsd::1.0", "Date");
    private final static QName _SpdxDocument_QNAME = new QName("spdx:xsd::1.0", "SpdxDocument");
    private final static QName _LicenseListVersion_QNAME = new QName("spdx:xsd::1.0", "LicenseListVersion");
    private final static QName _Checksum_QNAME = new QName("spdx:xsd::1.0", "Checksum");
    private final static QName _DescribesPackage_QNAME = new QName("spdx:xsd::1.0", "DescribesPackage");
    private final static QName _SpdxElement_QNAME = new QName("spdx:xsd::1.0", "SpdxElement");
    private final static QName _CreationInfo_QNAME = new QName("spdx:xsd::1.0", "CreationInfo");
    private final static QName _ExternalDocumentRef_QNAME = new QName("spdx:xsd::1.0", "ExternalDocumentRef");
    private final static QName _DataLicense_QNAME = new QName("spdx:xsd::1.0", "DataLicense");
    private final static QName _DescribesFile_QNAME = new QName("spdx:xsd::1.0", "DescribesFile");
    private final static QName _Creator_QNAME = new QName("spdx:xsd::1.0", "Creator");
    private final static QName _Created_QNAME = new QName("spdx:xsd::1.0", "Created");
    private final static QName _Name_QNAME = new QName("spdx:xsd::1.0", "Name");
    private final static QName _AlgorithmCode_QNAME = new QName("spdx:xsd::1.0", "AlgorithmCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: spdx.xsd._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SpdxElementType }
     * 
     */
    public SpdxElementType createSpdxElementType() {
        return new SpdxElementType();
    }

    /**
     * Create an instance of {@link CreationInfoType }
     * 
     */
    public CreationInfoType createCreationInfoType() {
        return new CreationInfoType();
    }

    /**
     * Create an instance of {@link ExternalDocumentRefType }
     * 
     */
    public ExternalDocumentRefType createExternalDocumentRefType() {
        return new ExternalDocumentRefType();
    }

    /**
     * Create an instance of {@link LicenseIDType }
     * 
     */
    public LicenseIDType createLicenseIDType() {
        return new LicenseIDType();
    }

    /**
     * Create an instance of {@link SpdxDocumentType }
     * 
     */
    public SpdxDocumentType createSpdxDocumentType() {
        return new SpdxDocumentType();
    }

    /**
     * Create an instance of {@link CreatorType }
     * 
     */
    public CreatorType createCreatorType() {
        return new CreatorType();
    }

    /**
     * Create an instance of {@link AlgorithmCodeType }
     * 
     */
    public AlgorithmCodeType createAlgorithmCodeType() {
        return new AlgorithmCodeType();
    }

    /**
     * Create an instance of {@link CreatedType }
     * 
     */
    public CreatedType createCreatedType() {
        return new CreatedType();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link LicenseListVersionType }
     * 
     */
    public LicenseListVersionType createLicenseListVersionType() {
        return new LicenseListVersionType();
    }

    /**
     * Create an instance of {@link ChecksumType }
     * 
     */
    public ChecksumType createChecksumType() {
        return new ChecksumType();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link AnnotationType }
     * 
     */
    public AnnotationType createAnnotationType() {
        return new AnnotationType();
    }

    /**
     * Create an instance of {@link DateType }
     * 
     */
    public DateType createDateType() {
        return new DateType();
    }

    /**
     * Create an instance of {@link RelationshipTypeCodeType }
     * 
     */
    public RelationshipTypeCodeType createRelationshipTypeCodeType() {
        return new RelationshipTypeCodeType();
    }

    /**
     * Create an instance of {@link ExternalDocumentIDType }
     * 
     */
    public ExternalDocumentIDType createExternalDocumentIDType() {
        return new ExternalDocumentIDType();
    }

    /**
     * Create an instance of {@link SpecVersionType }
     * 
     */
    public SpecVersionType createSpecVersionType() {
        return new SpecVersionType();
    }

    /**
     * Create an instance of {@link AnnotatorType }
     * 
     */
    public AnnotatorType createAnnotatorType() {
        return new AnnotatorType();
    }

    /**
     * Create an instance of {@link ChecksumValueType }
     * 
     */
    public ChecksumValueType createChecksumValueType() {
        return new ChecksumValueType();
    }

    /**
     * Create an instance of {@link AnnotationTypeCodeType }
     * 
     */
    public AnnotationTypeCodeType createAnnotationTypeCodeType() {
        return new AnnotationTypeCodeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "RelationshipTypeCode")
    public JAXBElement<RelationshipTypeCodeType> createRelationshipTypeCode(RelationshipTypeCodeType value) {
        return new JAXBElement<RelationshipTypeCodeType>(_RelationshipTypeCode_QNAME, RelationshipTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Annotator")
    public JAXBElement<AnnotatorType> createAnnotator(AnnotatorType value) {
        return new JAXBElement<AnnotatorType>(_Annotator_QNAME, AnnotatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChecksumValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "ChecksumValue")
    public JAXBElement<ChecksumValueType> createChecksumValue(ChecksumValueType value) {
        return new JAXBElement<ChecksumValueType>(_ChecksumValue_QNAME, ChecksumValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalDocumentIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "ExternalDocumentID")
    public JAXBElement<ExternalDocumentIDType> createExternalDocumentID(ExternalDocumentIDType value) {
        return new JAXBElement<ExternalDocumentIDType>(_ExternalDocumentID_QNAME, ExternalDocumentIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecVersionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "SpecVersion")
    public JAXBElement<SpecVersionType> createSpecVersion(SpecVersionType value) {
        return new JAXBElement<SpecVersionType>(_SpecVersion_QNAME, SpecVersionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Relationship")
    public JAXBElement<RelationshipType> createRelationship(RelationshipType value) {
        return new JAXBElement<RelationshipType>(_Relationship_QNAME, RelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationTypeCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "AnnotationTypeCode")
    public JAXBElement<AnnotationTypeCodeType> createAnnotationTypeCode(AnnotationTypeCodeType value) {
        return new JAXBElement<AnnotationTypeCodeType>(_AnnotationTypeCode_QNAME, AnnotationTypeCodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "HasExtractedLicensingInfo")
    public JAXBElement<SpdxDocumentType> createHasExtractedLicensingInfo(SpdxDocumentType value) {
        return new JAXBElement<SpdxDocumentType>(_HasExtractedLicensingInfo_QNAME, SpdxDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Comment")
    public JAXBElement<CommentType> createComment(CommentType value) {
        return new JAXBElement<CommentType>(_Comment_QNAME, CommentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "RelatedSpdxElement")
    public JAXBElement<RelationshipType> createRelatedSpdxElement(RelationshipType value) {
        return new JAXBElement<RelationshipType>(_RelatedSpdxElement_QNAME, RelationshipType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Annotation")
    public JAXBElement<AnnotationType> createAnnotation(AnnotationType value) {
        return new JAXBElement<AnnotationType>(_Annotation_QNAME, AnnotationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Date")
    public JAXBElement<DateType> createDate(DateType value) {
        return new JAXBElement<DateType>(_Date_QNAME, DateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "SpdxDocument")
    public JAXBElement<SpdxDocumentType> createSpdxDocument(SpdxDocumentType value) {
        return new JAXBElement<SpdxDocumentType>(_SpdxDocument_QNAME, SpdxDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LicenseListVersionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "LicenseListVersion")
    public JAXBElement<LicenseListVersionType> createLicenseListVersion(LicenseListVersionType value) {
        return new JAXBElement<LicenseListVersionType>(_LicenseListVersion_QNAME, LicenseListVersionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChecksumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Checksum")
    public JAXBElement<ChecksumType> createChecksum(ChecksumType value) {
        return new JAXBElement<ChecksumType>(_Checksum_QNAME, ChecksumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "DescribesPackage")
    public JAXBElement<SpdxDocumentType> createDescribesPackage(SpdxDocumentType value) {
        return new JAXBElement<SpdxDocumentType>(_DescribesPackage_QNAME, SpdxDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "SpdxElement")
    public JAXBElement<SpdxElementType> createSpdxElement(SpdxElementType value) {
        return new JAXBElement<SpdxElementType>(_SpdxElement_QNAME, SpdxElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreationInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "CreationInfo")
    public JAXBElement<CreationInfoType> createCreationInfo(CreationInfoType value) {
        return new JAXBElement<CreationInfoType>(_CreationInfo_QNAME, CreationInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalDocumentRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "ExternalDocumentRef")
    public JAXBElement<ExternalDocumentRefType> createExternalDocumentRef(ExternalDocumentRefType value) {
        return new JAXBElement<ExternalDocumentRefType>(_ExternalDocumentRef_QNAME, ExternalDocumentRefType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LicenseIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "DataLicense")
    public JAXBElement<LicenseIDType> createDataLicense(LicenseIDType value) {
        return new JAXBElement<LicenseIDType>(_DataLicense_QNAME, LicenseIDType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "DescribesFile")
    public JAXBElement<SpdxDocumentType> createDescribesFile(SpdxDocumentType value) {
        return new JAXBElement<SpdxDocumentType>(_DescribesFile_QNAME, SpdxDocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Creator")
    public JAXBElement<CreatorType> createCreator(CreatorType value) {
        return new JAXBElement<CreatorType>(_Creator_QNAME, CreatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreatedType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Created")
    public JAXBElement<CreatedType> createCreated(CreatedType value) {
        return new JAXBElement<CreatedType>(_Created_QNAME, CreatedType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Name")
    public JAXBElement<NameType> createName(NameType value) {
        return new JAXBElement<NameType>(_Name_QNAME, NameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlgorithmCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "AlgorithmCode")
    public JAXBElement<AlgorithmCodeType> createAlgorithmCode(AlgorithmCodeType value) {
        return new JAXBElement<AlgorithmCodeType>(_AlgorithmCode_QNAME, AlgorithmCodeType.class, null, value);
    }

}
