//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 09:32:17 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RelationshipTypeCodeSimpleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RelationshipTypeCodeSimpleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Amendment"/>
 *     &lt;enumeration value="AncestorOf"/>
 *     &lt;enumeration value="BuildToolOf"/>
 *     &lt;enumeration value="ContainedBy"/>
 *     &lt;enumeration value="Contains"/>
 *     &lt;enumeration value="CopyOf"/>
 *     &lt;enumeration value="DataFileOf"/>
 *     &lt;enumeration value="DescendantOf"/>
 *     &lt;enumeration value="DescribedBy"/>
 *     &lt;enumeration value="Describes"/>
 *     &lt;enumeration value="DistributionArtifact"/>
 *     &lt;enumeration value="Documentation"/>
 *     &lt;enumeration value="DynamicLink"/>
 *     &lt;enumeration value="ExpandedFromArchive"/>
 *     &lt;enumeration value="FileAdded"/>
 *     &lt;enumeration value="FileDeleted"/>
 *     &lt;enumeration value="FileModified"/>
 *     &lt;enumeration value="GeneratedFrom"/>
 *     &lt;enumeration value="Generates"/>
 *     &lt;enumeration value="HasPrerequisite"/>
 *     &lt;enumeration value="MetafileOf"/>
 *     &lt;enumeration value="OptionalComponentOf"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="PackageOf"/>
 *     &lt;enumeration value="PatchApplied"/>
 *     &lt;enumeration value="PatchFor"/>
 *     &lt;enumeration value="PrerequisiteFor"/>
 *     &lt;enumeration value="StaticLink"/>
 *     &lt;enumeration value="TestcaseOf"/>
 *     &lt;enumeration value="VariantOf"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RelationshipTypeCodeSimpleType")
@XmlEnum
public enum RelationshipTypeCodeSimpleType {


    /**
     * To be used when SPDXRef-A amends the SPDX information in SPDXRef-B.
     * 
     */
    @XmlEnumValue("Amendment")
    AMENDMENT("Amendment"),

    /**
     * A Relationship of relationshipType_ancestorOf expresses that an SPDXElement is an ancestor of (same lineage but pre-dates) the relatedSPDXElement. For example, an upstream File is an ancestor of a modified downstream File
     * 
     */
    @XmlEnumValue("AncestorOf")
    ANCESTOR_OF("AncestorOf"),

    /**
     * To be used when SPDXRef-A is used to to build SPDXRef-B.
     * 
     */
    @XmlEnumValue("BuildToolOf")
    BUILD_TOOL_OF("BuildToolOf"),

    /**
     * A Relationship of relationshipType_containedBy expresses that an SPDXElement is contained by the relatedSPDXElement. For example, a File contained by a Package.
     * 
     */
    @XmlEnumValue("ContainedBy")
    CONTAINED_BY("ContainedBy"),

    /**
     * A Relationship of relationshipType_contains expresses that an SPDXElement contains the relatedSPDXElement. For example, a Package contains a File. (relationshipType_contains introduced in SPDX 2.0 deprecates property 'hasFile' from SPDX 1.2)
     * 
     */
    @XmlEnumValue("Contains")
    CONTAINS("Contains"),

    /**
     * A Relationship of relationshipType_copyOf expresses that the SPDXElement is an exact copy of the relatedSDPXElement. For example, a downstream distribution of a binary library which was copied from the upstream package.
     * 
     */
    @XmlEnumValue("CopyOf")
    COPY_OF("CopyOf"),

    /**
     * Is to be used when SPDXRef-A is a data file used in SPDXRef-B.
     * 
     */
    @XmlEnumValue("DataFileOf")
    DATA_FILE_OF("DataFileOf"),

    /**
     * A Relationship of relationshipType_descendantOf expresses that an SPDXElement is a descendant of (same lineage but post-dates) the relatedSPDXElement. For example, an downstream File that was modified is a descendant of an upstream File
     * 
     */
    @XmlEnumValue("DescendantOf")
    DESCENDANT_OF("DescendantOf"),

    /**
     * Is to be used an SPDXRef-A is described by SPDXRef-Document.
     * 
     */
    @XmlEnumValue("DescribedBy")
    DESCRIBED_BY("DescribedBy"),

    /**
     * Is to be used when SPDXRef-DOCUMENT describes SPDXRef-A.
     * 
     */
    @XmlEnumValue("Describes")
    DESCRIBES("Describes"),

    /**
     * A Relationship of relationshipType_distributionArtifact expresses that distributing the SPDXElement requires that the relatedSPDXElement also be distributed. For example, distributing a binary File may require that a source tarball (another File) be made available with the distribuiton.
     * 
     */
    @XmlEnumValue("DistributionArtifact")
    DISTRIBUTION_ARTIFACT("DistributionArtifact"),

    /**
     * Website containing the documentation related to the repository identifier
     * 
     */
    @XmlEnumValue("Documentation")
    DOCUMENTATION("Documentation"),

    /**
     * Is to be used when SPDXRef-A dynamically links to SPDXRef-B.
     * 
     */
    @XmlEnumValue("DynamicLink")
    DYNAMIC_LINK("DynamicLink"),

    /**
     * A Relationship of relationshipType_expandedFromArchive expresses that the SPDXElement is a file which was epanded from a relatedSPDXElement file. For example, if there is an archive file xyz.tar.gz containing a file foo.c the archive file was expanded in a directory arch/xyz, the file arch/xyz/foo.c would have a relationshipType_expandedFromArchive with the file xyz.tar.gz.
     * 
     */
    @XmlEnumValue("ExpandedFromArchive")
    EXPANDED_FROM_ARCHIVE("ExpandedFromArchive"),

    /**
     * A Relationship of relationshipType_fileAdded expresses that the SPDXElement is a file which has been added to the relatedSPDXElement package. For example, a package (the relatedSPDXElement) has been patched to remove a file (the SPDXElement). This relationship is typically used to express the result of a patched package when the actual patchfile is not present.
     * 
     */
    @XmlEnumValue("FileAdded")
    FILE_ADDED("FileAdded"),

    /**
     * A Relationship of relationshipType_fileDeleted expresses that the SPDXElement is a package where the relatedSPDXElement file has been removed. For example, a package has been patched to remove a file a file (the relatedSPDXElement resulting in the patched package (the SPDXElement). This relationship is typically used to express the result of a patched package when the actual patchfile is not present.
     * 
     */
    @XmlEnumValue("FileDeleted")
    FILE_DELETED("FileDeleted"),

    /**
     * A Relationship of relationshipType_fileModified expresses that the SPDXElement is a file which is a modified version of the relatedSPDXElement file. For example, a file (the SPDXElement) has been patched to modify the contents of the original file (the SPDXElement). This relationship is typically used to express the result of a patched package when the actual patchfile is not present.
     * 
     */
    @XmlEnumValue("FileModified")
    FILE_MODIFIED("FileModified"),

    /**
     * A Relationship of relationshipType_generatedFrom expresses that an SPDXElement was generated from the relatedSPDXElement. For example, a binary File might have been generated from a source File.
     * 
     */
    @XmlEnumValue("GeneratedFrom")
    GENERATED_FROM("GeneratedFrom"),

    /**
     * A Relationship of relationshipType_generates expresses that an SPDXElement generates the relatedSPDXElement. For example, a source File generates a binary File.
     * 
     */
    @XmlEnumValue("Generates")
    GENERATES("Generates"),

    /**
     * Is to be used when SPDXRef-A has as a prerequisite SPDXRef-B.
     * 
     */
    @XmlEnumValue("HasPrerequisite")
    HAS_PREREQUISITE("HasPrerequisite"),

    /**
     * To be used when SPDXRef-A is a metafile of SPDXRef-B.
     * 
     */
    @XmlEnumValue("MetafileOf")
    METAFILE_OF("MetafileOf"),

    /**
     * To be used when SPDXRef-A is an optional component of SPDXRef-B.
     * 
     */
    @XmlEnumValue("OptionalComponentOf")
    OPTIONAL_COMPONENT_OF("OptionalComponentOf"),

    /**
     * Type of annotation which does not fit in any of the pre-defined annotation types.
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other"),

    /**
     * To be used when SPDXRef-A is used as a package as part of SPDXRef-B.
     * 
     */
    @XmlEnumValue("PackageOf")
    PACKAGE_OF("PackageOf"),

    /**
     * A Relationship of relationshipType_patchApplied expresses that the SPDXElement is a 'patchfile' that was applied and produced the relatedSPDXElement. For example, a .diff File relates to a specific file where the diff was applied.
     * 
     */
    @XmlEnumValue("PatchApplied")
    PATCH_APPLIED("PatchApplied"),

    /**
     * A Relationship of relationshipType_patchFor expresses that the SPDXElement is a 'patchfile' that is designed to patch (apply modifications to) the relatedSPDXElement. For example, relationship from a .diff File to a Package it is designed to patch.
     * 
     */
    @XmlEnumValue("PatchFor")
    PATCH_FOR("PatchFor"),

    /**
     * Is to be used when SPDXRef-A is a prerequisite for SPDXRef-B
     * 
     */
    @XmlEnumValue("PrerequisiteFor")
    PREREQUISITE_FOR("PrerequisiteFor"),

    /**
     * Is to be used when SPDXRef-A statically links to SPDXRef-B.
     * 
     */
    @XmlEnumValue("StaticLink")
    STATIC_LINK("StaticLink"),

    /**
     * Is to be used when SPDXRef-A is a test case used in testing SPDXRef-B.
     * 
     */
    @XmlEnumValue("TestcaseOf")
    TESTCASE_OF("TestcaseOf"),

    /**
     * A Relationship of relationshipType_variantOf expresses that an SPDXElement is a variant of the relatedSPDXElement, but it is not clear which came first. For example, if the content of two Files differs by some edit, but there is no way to tell which came first (no reliable date information), then one File is a variant of the other File.
     * 
     */
    @XmlEnumValue("VariantOf")
    VARIANT_OF("VariantOf");
    private final String value;

    RelationshipTypeCodeSimpleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RelationshipTypeCodeSimpleType fromValue(String v) {
        for (RelationshipTypeCodeSimpleType c: RelationshipTypeCodeSimpleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
