//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.31 at 09:32:17 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for SpdxDocument type
 * 
 * <p>Java class for SpdxDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpdxDocumentType">
 *   &lt;complexContent>
 *     &lt;extension base="{spdx:xsd::1.0}SpdxElementType">
 *       &lt;sequence>
 *         &lt;element ref="{spdx:xsd::1.0}DescribesPackage" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}DescribesFile" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}HasExtractedLicensingInfo" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}CreationInfo"/>
 *         &lt;element ref="{spdx:xsd::1.0}SpecVersion"/>
 *         &lt;element ref="{spdx:xsd::1.0}ExternalDocumentRef" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}DataLicense"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpdxDocumentType", propOrder = {
    "describesPackage",
    "describesFile",
    "hasExtractedLicensingInfo",
    "creationInfo",
    "specVersion",
    "externalDocumentRef",
    "dataLicense"
})
public class SpdxDocumentType
    extends SpdxElementType
{

    @XmlElement(name = "DescribesPackage", nillable = true)
    protected SpdxDocumentType describesPackage;
    @XmlElement(name = "DescribesFile", nillable = true)
    protected SpdxDocumentType describesFile;
    @XmlElement(name = "HasExtractedLicensingInfo", nillable = true)
    protected SpdxDocumentType hasExtractedLicensingInfo;
    @XmlElement(name = "CreationInfo", required = true, nillable = true)
    protected CreationInfoType creationInfo;
    @XmlElement(name = "SpecVersion", required = true, nillable = true)
    protected SpecVersionType specVersion;
    @XmlElement(name = "ExternalDocumentRef", nillable = true)
    protected ExternalDocumentRefType externalDocumentRef;
    @XmlElement(name = "DataLicense", required = true, nillable = true)
    protected LicenseIDType dataLicense;

    /**
     * Gets the value of the describesPackage property.
     * 
     * @return
     *     possible object is
     *     {@link SpdxDocumentType }
     *     
     */
    public SpdxDocumentType getDescribesPackage() {
        return describesPackage;
    }

    /**
     * Sets the value of the describesPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpdxDocumentType }
     *     
     */
    public void setDescribesPackage(SpdxDocumentType value) {
        this.describesPackage = value;
    }

    /**
     * Gets the value of the describesFile property.
     * 
     * @return
     *     possible object is
     *     {@link SpdxDocumentType }
     *     
     */
    public SpdxDocumentType getDescribesFile() {
        return describesFile;
    }

    /**
     * Sets the value of the describesFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpdxDocumentType }
     *     
     */
    public void setDescribesFile(SpdxDocumentType value) {
        this.describesFile = value;
    }

    /**
     * Gets the value of the hasExtractedLicensingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SpdxDocumentType }
     *     
     */
    public SpdxDocumentType getHasExtractedLicensingInfo() {
        return hasExtractedLicensingInfo;
    }

    /**
     * Sets the value of the hasExtractedLicensingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpdxDocumentType }
     *     
     */
    public void setHasExtractedLicensingInfo(SpdxDocumentType value) {
        this.hasExtractedLicensingInfo = value;
    }

    /**
     * Gets the value of the creationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreationInfoType }
     *     
     */
    public CreationInfoType getCreationInfo() {
        return creationInfo;
    }

    /**
     * Sets the value of the creationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfoType }
     *     
     */
    public void setCreationInfo(CreationInfoType value) {
        this.creationInfo = value;
    }

    /**
     * Gets the value of the specVersion property.
     * 
     * @return
     *     possible object is
     *     {@link SpecVersionType }
     *     
     */
    public SpecVersionType getSpecVersion() {
        return specVersion;
    }

    /**
     * Sets the value of the specVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecVersionType }
     *     
     */
    public void setSpecVersion(SpecVersionType value) {
        this.specVersion = value;
    }

    /**
     * Gets the value of the externalDocumentRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalDocumentRefType }
     *     
     */
    public ExternalDocumentRefType getExternalDocumentRef() {
        return externalDocumentRef;
    }

    /**
     * Sets the value of the externalDocumentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalDocumentRefType }
     *     
     */
    public void setExternalDocumentRef(ExternalDocumentRefType value) {
        this.externalDocumentRef = value;
    }

    /**
     * Gets the value of the dataLicense property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseIDType }
     *     
     */
    public LicenseIDType getDataLicense() {
        return dataLicense;
    }

    /**
     * Sets the value of the dataLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseIDType }
     *     
     */
    public void setDataLicense(LicenseIDType value) {
        this.dataLicense = value;
    }

}
